version: "3.9"

services:
  frontend-service:
    build: ../frontend-service
    container_name: frontend-service
    ports:
      - "8000:8000"
    depends_on:
      - api-service
      - otel-collector

  api-service:
    build: ../api-service
    container_name: api-service
    ports:
      - "8001:8000"
    depends_on:
      - worker-service
      - otel-collector

  worker-service:
    build: ../worker-service
    container_name: worker-service
    ports:
      - "8002:8000"
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    ports:
      - "14317:4317"
      - "14318:4318"
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml
    command: [ "--config=/etc/otel/config.yaml" ]

  jaeger:
    image: jaegertracing/all-in-one:1.52
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC ingestion
      - "4318:4318"    # OTLP HTTP ingestion
