"""
Tests for validating detection of pandas‑generated ``Unnamed:`` headers.

This module verifies that the Cleaner correctly rejects CSV files whose
column headers are missing or implicitly generated by pandas (e.g.,
``Unnamed: 0``, ``Unnamed: 1``). Such headers indicate that the CSV file
either lacks a proper header row or contains empty header fields. The
Cleaner is expected to treat these as invalid and raise a ValueError.
"""

import os
import pytest

from csv_cleaner.cleaner import Cleaner


def test_unnamed_headers():
    """
    Ensure the Cleaner raises ValueError when encountering ``Unnamed:``
    columns produced by pandas due to missing or empty header fields.

    This test loads a CSV file intentionally crafted with missing header
    names. When pandas reads such a file, it auto‑generates placeholder
    column names like ``Unnamed: 0``. The Cleaner is expected to detect
    these placeholders during schema validation and reject the file.

    Steps
    -----
    1. Build a stable path to ``tests/data/unnamed_headers.csv``.
    2. Instantiate the Cleaner with an empty configuration.
    3. Assert that calling ``clean()`` raises ``ValueError`` because the
       CSV contains ``Unnamed:`` columns.

    Raises
    ------
    AssertionError
        If the Cleaner does not raise ValueError for auto‑generated
        ``Unnamed:`` headers.
    """
    # Path to the CSV file containing pandas-generated Unnamed headers
    test_dir: str = os.path.dirname(__file__)
    file_path = os.path.join(test_dir, "data", "unnamed_headers.csv")

    cleaner = Cleaner(config={})

    # Expect ValueError because the CSV contains 'Unnamed:' columns
    with pytest.raises(ValueError):
        cleaner.clean(file_path)
